# Name of the website
title: KoL Scripting Resources

# Description of the website
description: A grand array of resources for Junior Associate Loathing Engineer Newbies

# Don't give a download link. Nobody needs this.
show_downloads: false

# Your name to show in the footer
author: L. A. S. S.

remote_theme: pages-themes/minimal@v0.2.0

baseurl: KoL-Scripting-Resources/

# the actual url
url: https://loathers.github.io/
repository: loathers/loathers.net

# To populate, add a descriptive title and the name of the file w/ html
#   instead of md. Put it under sublinks if you would like.
navbarData: 
  - title: An Introduction to KOL Scripting
    url: KoL-Scripting-Introduction.html
  - title: ASH Overview
    url: ASH-Overview.html
  - title: JavaScript Overview
    url: JS-Overview.html
  - title: How to make a Pull Request
    url: PR-Overview.html
  - title: Lists of Scripts
    sublinks:
      - title: Community Service Scripts
        url: CS-Scripting-Resources.html
      - title: Awesome KoL Scripts
        url: Awesome-Scripts.html
  - title: How to Script CS
    url: Scripting-CS.html

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# When testing locally, remember to run:
#   $env:path += "C:\Ruby30-x64\bin;"
#   bundle install
#   and then bundle exec jekyll serve
# due to how much windows hates Ruby and will not play nicely with its binaries 
